spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-yeogida.czfim5awnvs3.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: yeogida123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace