cloud:
  aws:
    credentials:
      access-key: AKIAQBVIBHZWZNF6DVPO
      secret-key: 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

rds:
  url: jdbc:mysql://database-yeogida.czfim5awnvs3.ap-northeast-2.rds.amazonaws.com:3306/yeogida
  username: admin
  password: yeogida123


jwt:
  secret-key: 0e7cd9f102c251f716731901621f0bfac6b3f4797a3a5c9de4806f184ec40cc106627dfe481e7f2cbc67569b2f62c8c61b2b7d6ca8193df585cd256aeea6baf1

slack:
#  token: xoxb-4175653470198-4568427167764-TqhmPrcRL5JDdkoTUSqxbTkD
#  channel:
#    monitor: '#team-yeogida'
  webhook:
    url: https://hooks.slack.com/services/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
