spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-yeogida.czfim5awnvs3.ap-northeast-2.rds.amazonaws.com:3306/yeogida
    username: admin
    password: yeogida123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

jwt:
  header: Authorization
  secret: 0e7cd9f102c251f716731901621f0bfac6b3f4797a3a5c9de4806f184ec40cc106627dfe481e7f2cbc67569b2f62c8c61b2b7d6ca8193df585cd256aeea6baf1