spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/yeogida
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.amazonaws.util.EC2MetadataUtils: ERROR

jwt:
  header: Authorization
  secret: ${jwt.secret-key}